name: Pylint Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'  # Adjust to your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f Bot/requirements.txt ]; then pip install -r Bot/requirements.txt; fi
          if [ -f Flask/requirements.txt ]; then pip install -r Flask/requirements.txt; fi

      - name: Run Pylint Flask
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/Flask
          cd Flask
          pylint app/*.py app/**/*.py
      - name: Run Pylint Bot
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/Bot
          cd Bot
          pylint app/*.py app/**/*.py
